version: '3.8'

services:
  # WhatsApp Bridge Service (Go)
  whatsapp-bridge:
    build:
      context: .
      dockerfile: ./Dockerfiles/bridge
    volumes:
      - ./data/store:/app/store
      - ./data/media:/app/media
    environment:
      - CGO_ENABLED=1
    networks:
      - whatsapp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP Server (Python)
  mcp-server:
    build:
      context: .
      dockerfile: ./Dockerfiles/mcp
    environment:
      - WHATSAPP_API_BASE_URL=http://whatsapp-bridge:8080/api
      - MESSAGES_DB_PATH=/app/data/store/messages.db
    volumes:
      - ./data:/app/data
    networks:
      - whatsapp-network
    depends_on:
      whatsapp-bridge:
        condition: service_healthy
    restart: unless-stopped

  # API Server (Python)
  api-server:
    build:
      context: .
      dockerfile: ./Dockerfiles/api
    environment:
      - WHATSAPP_API_BASE_URL=http://whatsapp-bridge:8080/api
      - API_KEY=${API_KEY:-mysecretkey}
    networks:
      - whatsapp-network
    depends_on:
      whatsapp-bridge:
        condition: service_healthy
    restart: unless-stopped

networks:
  whatsapp-network:
    driver: bridge

volumes:
  whatsapp-data:
    driver: local
